services:
  flask_api:
    build:
      context: .
    command: python flask_api/api.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  streamlit_app:
    build:
      context: .
    command: streamlit run streamlit_app/Home.py
    ports:
      - "8501:8501"
    depends_on:
      - flask_api
    volumes:
      - .:/app
