services:
  flask_api:
    build:
      context: ./flask_api
    container_name: flask_api
    ports:
      - "5000:5000"
    restart: always

  streamlit_app:
    build:
      context: ./streamlit_app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - flask_api
    restart: always
